### PR TITLE
✨ (rc): Set custom robot name

### PR DESCRIPTION
**Pull request by YannLocatelli**
# Requirements

- [x] #1258

# Related issues

- #894 
- #1097

### CODE REVIEW

**Review by HPezz — APPROVED** [review]
Nice job 👍 

- [x] Validated on robot 
IMG_CCFBA5EFC07F-1

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Review by HPezz — COMMENTED** [review]
Nice work, just a thing to discuss.

Special character like é/à/$/etc.. are not allowed and induce BLE crash on reboot after a renaming. Will those special characters be proceed by the app or by the robot with PR.

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Pull request merged**
