### PR TITLE
✨ (rc): Add FileExchange state and actions

### PR DESCRIPTION
**Pull request by YannLocatelli**
## Need

* [x] #1129
* [ ] #1130

## Related issues & PR

* #1067
* #1050
* #899

### CODE REVIEW

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Review by HPezz — COMMENTED** [review]
LGTM

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Review by HPezz — APPROVED** [review]
Good

**Pull request merged**
