### PR TITLE
✨ (rc): Update advertising data in BLE with battery and charging status (alternative)

### PR DESCRIPTION
**Pull request by YannLocatelli**
Based on #755 and #736 

- [x] Validated on robot (spike lk_ble, 20/05/2022)

### CODE REVIEW

**Review by ladislas — APPROVED** [review]
LGTM 👍

**Comment by YannLocatelli** [comment]
Rebased

**Comment by YannLocatelli** [comment]
Rebased

**Comment by YannLocatelli** [comment]
Once merged, #755 should be closed

**Pull request merged**
